<template>
  <div>
    dfasdfasdf
  </div>
</template>
<script>
export default {
  name: 'a',
  props: {
    // aaa: {
    //   type: Object,
    //   default: () => {
    //     return {
    //       name: ''
    //     }
    //   },
    //   required: true
    // }
  },
  data () {
    return {}
  },
  created () { },
  mounted () { },
  methods: {},
  computed: {
    aaaFunction () {
      return ''
    }
  },
  watch: {
    tableData (newQuestion, oldQuestion) {
    }
  },
  components: {}
}
</script>
<style lang="css" scoped>

</style>
